version: '3.7'

services:
  php:
    build:
      target: dev
    environment:
      - TZ=Europe/Kiev
      - PHP_IDE_CONFIG=serverName=${DEBUG_SERVER_NAME}
      - XDEBUG_CONFIG=remote_host=${DEBUG_REMOTE_HOST} remote_port=${DEBUG_REMOTE_PORT} idekey=${DEBUG_IDEKEY}
      - APP_NAME=Test-Laravel
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - APP_TIMEZONE=Europe/Kiev
      - LOG_CHANNEL=stack
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE_FILE=/run/secrets/mysql-db
      - DB_USERNAME_FILE=/run/secrets/mysql-user
      - DB_PASSWORD_FILE=/run/secrets/mysql-pw
#      - DB_CONNECTION=pgsql
#      - DB_HOST_MANAGEMENT=postgres
#      - DB_PORT_MANAGEMENT=5432
#      - DB_DATABASE_MANAGEMENT_FILE=/run/secrets/psql-db
#      - DB_USERNAME_MANAGEMENT_FILE=/run/secrets/psql-user
#      - DB_PASSWORD_MANAGEMENT_FILE=/run/secrets/psql-pw
#      - DB_CONNECTION_DRAFT=mongodb
#      - DB_HOST_DRAFT=mongo
#      - DB_PORT_DRAFT=27017
#      - DB_DATABASE_DRAFT_FILE=/run/secrets/mongo-db
#      - DB_USERNAME_DRAFT_FILE=/run/secrets/mongo-user
#      - DB_PASSWORD_DRAFT_FILE=/run/secrets/mongo-pw
#      - JWT_SECRET_FILE=/run/secrets/jwt-secret
#      - DATAPORTEN_KEY_FILE=/run/secrets/dataporten-key
#      - DATAPORTEN_SECRET_FILE=/run/secrets/dataporten-secret
#      - DATAPORTEN_REDIRECT_URI=http://test.local/dataporten
#      - FILESYSTEM_DRIVER=public_uploads
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - REDIS_HOST=127.0.0.1
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - MAIL_DRIVER=smtp
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
      - MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
    secrets:
      - mysql-user
      - mysql-pw
      - mysql-db
    volumes:
      - ./../back:/var/www/back

  nginx:
    build:
      target: dev
    environment:
      - TZ=Europe/Kiev
    ports:
      - 80:80
    volumes:
      - ./../back:/var/www/back

  mysql:
    build:
      target: dev
    environment:
      - TZ=Europe/Kiev
      - MYSQL_USER_FILE=/run/secrets/mysql-user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql-pw
      - MYSQL_DB_FILE=/run/secrets/mysql-db
      - MYSQL_ROOT_PASSWORD=admin!!
    secrets:
      - mysql-user
      - mysql-pw
      - mysql-db
    ports:
      - 3306:3306
    volumes:
      - ./mysql/volumes:/var/lib/mysql/data

secrets:
  mysql-user:
    file: ./mysql/mysql-fake-user.txt
  mysql-pw:
    file: ./mysql/mysql-fake-password.txt
  mysql-db:
    file: ./mysql/mysql-fake-db.txt
