version: '3.7'

services:
  php:
    image: temabok-php
    build:
      context: ./../temabok-back
      dockerfile: devops/php/Dockerfile
    container_name: temabok-api
    depends_on:
      - postgres
      - mongo

  dashboard-frontend-static:
    image: temabok-dashboard-frontend-static
    build:
      context: ./../temabok-front
      dockerfile: ./devops/Dockerfile

  nginx:
    image: temabok-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: temabok-nginx
    depends_on:
      - php

  postgres:
    image: temabok-postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: temabok-postgres

  mongo:
    image: temabok-mongo
    build:
      context: ./mongo
      dockerfile: Dockerfile
    container_name: temabok-mongo
