version: '3'
services:
    php-fpm:
      build:
          context: ./php-fpm
      container_name: php-fpm
      volumes:
          - ./../:/var/www/back
      links:
        - mysql
      environment:
        - TZ=Europe/Kiev
        - APP_NAME=Laravel
        - APP_ENV=local
        - APP_DEBUG=true
        - APP_URL=http://admin-panel.local

        - LOG_CHANNEL=stack

        - DB_CONNECTION=mysql
        - DB_HOST=mysql
        - DB_PORT=3306
        - DB_DATABASE=admin-panel
        - DB_USERNAME=admin
        - DB_PASSWORD=admin!

        - BROADCAST_DRIVER=log
        - CACHE_DRIVER=file
        - QUEUE_CONNECTION=sync
        - SESSION_DRIVER=file
        - SESSION_LIFETIME=120

        - REDIS_HOST=127.0.0.1
        - REDIS_PASSWORD=null
        - REDIS_PORT=6379

        - MAIL_DRIVER=smtp
        - MAIL_HOST=smtp.mailtrap.io
        - MAIL_PORT=2525
        - MAIL_USERNAME=null
        - MAIL_PASSWORD=null
        - MAIL_ENCRYPTION=null

        - MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
        - MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

### MySQL ################################################
    mysql:
      build:
        context: ./mysql
      container_name: mysql
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_PATH_HOST}:/var/lib/mysql
#        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"

  ### NGINX Server #########################################
    nginx:
      build:
        context: ./nginx
      container_name: nginx
      volumes:
        - ./../:/var/www/back
#        - ./nginx/conf.d/:/etc/nginx/conf.d/
#      volumes:
#        - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
#        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
#        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
#        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
