version: '3.7'

services:
  php:
    image: php
    build:
      context: ./../
      dockerfile: ./docker/php/Dockerfile
    container_name: api
    depends_on:
      - mysql

#  dashboard-frontend-static:
#    image: temabok-dashboard-frontend-static
#    build:
#      context: ./../temabok-front
#      dockerfile: ./devops/Dockerfile

  nginx:
    image: nginx
    build:
      context: ./../
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - php

  mysql:
    image: mysql
    build:
      context: ./../
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mysql
