version: '3.7'

services:
  php-fpm:
    build:
      target: dev
    expose:
      - "9000"
    environment:
      - TZ=Europe/Kiev
      - PHP_IDE_CONFIG=serverName=${DEBUG_SERVER_NAME}
      - XDEBUG_CONFIG=remote_host=${DEBUG_REMOTE_HOST} remote_port=${DEBUG_REMOTE_PORT} idekey=${DEBUG_IDEKEY}
      - APP_NAME=Test-Laravel
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=http://admin-panel.local
      - APP_TIMEZONE=Europe/Kiev
      - LOG_CHANNEL=stack
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - MYSQL_DATABASE_FILE=/run/secrets/mysql-db
      - MYSQL_USER_FILE=/run/secrets/mysql-user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql-pw
#      - DB_CONNECTION=pgsql
#      - DB_HOST_MANAGEMENT=postgres
#      - DB_PORT_MANAGEMENT=5432
#      - DB_DATABASE_MANAGEMENT_FILE=/run/secrets/psql-db
#      - DB_USERNAME_MANAGEMENT_FILE=/run/secrets/psql-user
#      - DB_PASSWORD_MANAGEMENT_FILE=/run/secrets/psql-pw
#      - DB_CONNECTION_DRAFT=mongodb
#      - DB_HOST_DRAFT=mongo
#      - DB_PORT_DRAFT=27017
#      - DB_DATABASE_DRAFT_FILE=/run/secrets/mongo-db
#      - DB_USERNAME_DRAFT_FILE=/run/secrets/mongo-user
#      - DB_PASSWORD_DRAFT_FILE=/run/secrets/mongo-pw
#      - JWT_SECRET_FILE=/run/secrets/jwt-secret
#      - DATAPORTEN_KEY_FILE=/run/secrets/dataporten-key
#      - DATAPORTEN_SECRET_FILE=/run/secrets/dataporten-secret
#      - DATAPORTEN_REDIRECT_URI=http://test.local/dataporten
#      - FILESYSTEM_DRIVER=public_uploads
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - REDIS_HOST=127.0.0.1
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - MAIL_DRIVER=smtp
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
      - MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
    secrets:
      - mysql-user
      - mysql-pw
      - mysql-db
    volumes:
      - ./../back:/var/www/back

#  nginx:
#    build:
#      target: dev
#      args:
#        - PHP_UPSTREAM_CONTAINER=php-fpm
#        - PHP_UPSTREAM_PORT=9000
#    environment:
#      - TZ=Europe/Kiev
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ./../back:/var/www/back
#      - ./logs/nginx/:/var/log/nginx
#      - ./nginx/sites/:/etc/nginx/sites-available
#      - ./nginx/ssl/:/etc/nginx/ssl

  nginx:
    build:
      target: dev
#    environment:
#      - TZ=Europe/Kiev
    ports:
      - "8810:80"
      - "443:443"
    volumes:
      - ./../back:/var/www/back
#      - ./logs/nginx/:/var/log/nginx
#      - ./nginx/sites/:/etc/nginx/sites-available
#      - ./nginx/ssl/:/etc/nginx/ssl

  mysql:
    build:
      target: dev
    environment:
      - TZ=Europe/Kiev
      - MYSQL_USER_FILE=/run/secrets/mysql-user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql-pw
#      - MYSQL_DB_FILE=/run/secrets/mysql-db
#      - MYSQL_ROOT_PASSWORD=admin!!
#      - MYSQL_USER=admin
#      - MYSQL_PASSWORD=admin!
#      - MYSQL_DATABASE=admin-panel-test
      - MYSQL_DATABASE_FILE=/run/secrets/mysql-db
      - MYSQL_ROOT_PASSWORD=root!!
    secrets:
      - mysql-user
      - mysql-pw
      - mysql-db
    ports:
      - 3306:3306
    volumes:
      - ./mysql/volumes:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf

secrets:
  mysql-user:
    file: ./mysql/mysql-fake-user.txt
  mysql-pw:
    file: ./mysql/mysql-fake-password.txt
  mysql-db:
    file: ./mysql/mysql-fake-db.txt
